### ISSUE TITLE
failed build : stylus error

### ISSUE THREAD

**Issue by luluprat** [atoha/dbootstrap#103]
Hello

when i try to build i get this:

python build.py demoINFO:dbootstrap.build:Building demo to /var/www/library/thesociable-dbootstrap-559963f/build/demo
INFO:dbootstrap.build:Building CSS.
WARNING:dbootstrap.build.execute:Command stylus --include /var/www/library/thesociable-dbootstrap-559963f/source/nib/lib --include /var/www/library/thesociable-dbootstrap-559963f/source/dbootstrap/theme/dbootstrap /var/www/library/thesociable-dbootstrap-559963f/source/dbootstrap/theme/dbootstrap/index.styl exited with code 1
Traceback (most recent call last):
  File "build.py", line 308, in <module>
    raise SystemExit(main())
  File "build.py", line 77, in main
    dbootstrap_css_path
OSError: [Errno 2] No such file or directory

so i try 

stylus --include /var/www/library/thesociable-dbootstrap-559963f/source/nib/lib --include /var/www/library/thesociable-dbootstrap-559963f/source/dbootstrap/theme/dbootstrap /var/www/library/thesociable-dbootstrap-559963f/source/dbootstrap/theme/dbootstrap/index.styl
/usr/local/lib/node_modules/stylus/bin/stylus:607
              throw err;
                    ^
Error: failed to locate @import file nib.styl
    at Evaluator.visitImport (/usr/local/lib/node_modules/stylus/lib/visitor/evaluator.js:843:21)
    at Evaluator.Visitor.visit (/usr/local/lib/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/usr/local/lib/node_modules/stylus/lib/visitor/evaluator.js:140:18)
    at Evaluator.visitRoot (/usr/local/lib/node_modules/stylus/lib/visitor/evaluator.js:662:27)
    at Evaluator.Visitor.visit (/usr/local/lib/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/usr/local/lib/node_modules/stylus/lib/visitor/evaluator.js:140:18)
    at Evaluator.evaluate (/usr/local/lib/node_modules/stylus/lib/visitor/evaluator.js:215:15)
    at Renderer.render (/usr/local/lib/node_modules/stylus/lib/renderer.js:79:26)
    at /usr/local/lib/node_modules/stylus/bin/stylus:601:15
    at fs.js:292:14

any help would be apreciate

Lucile

**Comment by martinpengellyphillips** [comment]
Did you use the `--recursive` flag when cloning?

**Comment by luluprat** [comment]
no i did not

2014-07-17 15:35 GMT+02:00 Martin Pengelly-Phillips <
notifications@github.com>:

**Comment by martinpengellyphillips** [comment]
Ok - so the submodules won't have been loaded (nib is a submodule).

Try running the following from the root of the project and then attempt the build again:

``` bash
git submodule update --init --recursive
```

**Comment by bledari** [comment]
I guess this can be closed. Worked for me!
