### ISSUE TITLE
stylus error

### ISSUE THREAD

**Issue by bigfish** [atoha/dbootstrap#18]
After downloading / cloning latest dev version (nov 26, git commit: 173725f36354e4ffd94e10db998fc8e9e52dca27)
and running the build, I get this error from stylus:

/usr/local/lib/node_modules/stylus/bin/stylus:516
              throw err;
                    ^
Error: build/dbootstrap/theme/dbootstrap.styl:48
   44|         text-align: center;
   45|         vertical-align: middle;
   46|     }
   47| }

> 48| 
>    49| 

Failed to @extend ".bootstrap .dijitComboBox .dijitButtonNode"

```
at Normalizer.extend (/usr/local/lib/node_modules/stylus/lib/visitor/normalizer.js:212:24)
at Array.forEach (native)
at Normalizer.extend (/usr/local/lib/node_modules/stylus/lib/visitor/normalizer.js:210:17)
at Normalizer.visitGroup (/usr/local/lib/node_modules/stylus/lib/visitor/normalizer.js:137:8)
at Normalizer.Visitor.visit (/usr/local/lib/node_modules/stylus/lib/visitor/index.js:28:40)
at Normalizer.visitBlock (/usr/local/lib/node_modules/stylus/lib/visitor/normalizer.js:110:19)
at Normalizer.Visitor.visit (/usr/local/lib/node_modules/stylus/lib/visitor/index.js:28:40)
at Normalizer.visitBlock (/usr/local/lib/node_modules/stylus/lib/visitor/normalizer.js:110:19)
at Normalizer.Visitor.visit (/usr/local/lib/node_modules/stylus/lib/visitor/index.js:28:40)
at Normalizer.visitBlock (/usr/local/lib/node_modules/stylus/lib/visitor/normalizer.js:110:19)
```

I'm using stylus installed from NPM globally, version 0.31.0

**Comment by martinpengellyphillips** [comment]
I've been running it against an older version of Stylus (0.29.0). Let me check out that later version and see what the issue is.

**Comment by martinpengellyphillips** [comment]
Ok, think I have fixed this. Please pull latest master and let me know if it solves the issue for you.

**Comment by bigfish** [comment]
That does the trick, thanks :) Pulled latest, rebuilt, and no errors, css generated successfully.
