### ISSUE TITLE
Dbootstrap not running in the dojo themeTester

### ISSUE THREAD

**Issue by RuiBaiao** [atoha/dbootstrap#57]
Hello,

I'm fairly new to dojo and have been exploring the dbootstrap theme to enhance the look and feel for some apps for my company. I followed the guide and have built the dbootstrap theme to include in the project. I'm using the themeTester demo porject that is included in the dojo SDK. Here is how my dbootstrap theme is setup:

1 - added to dojo.js:

```
            packages:[{
            (...)
            {
           location: '../dbootstrap', //this is where the main.js file of bootstrap is contained
           name: 'dbootstrap'
        }],
```

2 - in themeTester.html:

```
require(["dbootstrap", ...], function(dbootstrap,...) {

});
```

3 - in themeTester.html:
Changed `<body class="claro">` to `<body class="dbootstrap">`

Ran the index.html in chrome and got this trace:

```
TypeError {} "TypeError: undefined is not a function
    at http://localhost:90/dojoTest/js/dbootstrap/main.js:39:49
    at Object.array.forEach (http://localhost:90/dojoTest/js/dojo/_base/array.js:251:6)
    at b._attachTemplateNodes (http://localhost:90/dojoTest/js/dbootstrap/main.js:38:39)
    at declare.buildRendering (http://localhost:90/dojoTest/js/dijit/_AttachMixin.js:88:9)
    at inherited (http://localhost:90/dojoTest/js/dojo/_base/declare.js:189:30)
    at declare.buildRendering (http://localhost:90/dojoTest/js/dijit/_TemplatedMixin.js:102:9)
    at inherited (http://localhost:90/dojoTest/js/dojo/_base/declare.js:189:30)
    at declare.buildRendering (http://localhost:90/dojoTest/js/dijit/form/MappedTextBox.js:66:9)
    at inherited (http://localhost:90/dojoTest/js/dojo/_base/declare.js:189:30)
    at declare.buildRendering (http://localhost:90/dojoTest/js/dijit/_HasDropDown.js:195:9)
    ----------------------------------------
    rejected at signalDeferred (http://localhost:90/dojoTest/js/dojo/Deferred.js:84:15)
    at signalListener (http://localhost:90/dojoTest/js/dojo/Deferred.js:58:4)
    at Array.then.promise.then (http://localhost:90/dojoTest/js/dojo/Deferred.js:258:5)
    at declare._beforeFillContent (http://localhost:90/dojoTest/js/dijit/_WidgetsInTemplateMixin.js:52:8)
    at declare.buildRendering (http://localhost:90/dojoTest/js/dijit/_AttachMixin.js:90:9)
    at inherited (http://localhost:90/dojoTest/js/dojo/_base/declare.js:189:30)
    at declare.buildRendering (http://localhost:90/dojoTest/js/dijit/_TemplatedMixin.js:102:9)
    at declare.create (http://localhost:90/dojoTest/js/dijit/_WidgetBase.js:398:9)
    at declare.postscript (http://localhost:90/dojoTest/js/dijit/_WidgetBase.js:334:9)
    at new <anonymous> (http://localhost:90/dojoTest/js/dojo/_base/declare.js:390:7)
    ----------------------------------------
Error
    at Array.then.promise.then (http://localhost:90/dojoTest/js/dojo/Deferred.js:252:24)
    at declare._beforeFillContent (http://localhost:90/dojoTest/js/dijit/_WidgetsInTemplateMixin.js:52:8)
    at declare.buildRendering (http://localhost:90/dojoTest/js/dijit/_AttachMixin.js:90:9)
    at inherited (http://localhost:90/dojoTest/js/dojo/_base/declare.js:189:30)
    at declare.buildRendering (http://localhost:90/dojoTest/js/dijit/_TemplatedMixin.js:102:9)
    at declare.create (http://localhost:90/dojoTest/js/dijit/_WidgetBase.js:398:9)
    at declare.postscript (http://localhost:90/dojoTest/js/dijit/_WidgetBase.js:334:9)
    at new <anonymous> (http://localhost:90/dojoTest/js/dojo/_base/declare.js:390:7)
    at declare._initButton (http://localhost:90/dojoTest/js/dijit/_editor/plugins/FontChoice.js:482:18)
    at declare.setEditor (http://localhost:90/dojoTest/js/dijit/_editor/_Plugin.js:170:9)" instrumentation.js:18
```

I've followed the "Integration > Standalone Package" guide. Any idea of what i'm setting up wrong? Do i need to add any link for styling like "<link rel="stylesheet" href="../../dijit/themes/claro/claro.css"/>" but for dbootstrap? I'm pretty much lost at the moment. Any ideas?

**Comment by martinpengellyphillips** [comment]
To help narrow down what might be going wrong can you try and build the demo (`python build.py demo`) and test if that works in your browser? 

Also, let me know your OS and Chrome version.

**Comment by RuiBaiao** [comment]
The demo is built and running well. 

OS: Windows 8
Chrome: Version 26.0.1410.64 m

**Comment by martinpengellyphillips** [comment]
Cool - and which version of Dojo are you using?

**Comment by RuiBaiao** [comment]
Dojo 1.9

**Comment by martinpengellyphillips** [comment]
Ah, ok. There are a couple of issues regarding using Dojo 1.9 (#47, #53, #54, #58) that are currently being worked on. You can check out those branches and test or wait a bit for them to be merged to master.

**Comment by RuiBaiao** [comment]
Ok, will it work ok in ojo 1.8 and below though? If dbootstrap does not work in 1.9 but works in 1.8, it's ok for my purpose

**Comment by martinpengellyphillips** [comment]
Should work fine with 1.8. Note that the 1.9 fixes will be merged soon though so I would keep an eye on the issue list if moving to 1.9 is important for you.

**Comment by RuiBaiao** [comment]
Alright. Thank you for the feedback! I'll test it now with 1.7 actually, because it's more commonly used here. For research purposes i tried first with the more recent version, but in this case, given that we use 1.7 more frequently, i'll try with 1.7

**Comment by martinpengellyphillips** [comment]
How did you get on with 1.7?

**Comment by martinpengellyphillips** [comment]
Updated to Dojo 1.9.
