### ISSUE TITLE
Node Build Error - "Error: spawn ENOENT"

### ISSUE THREAD

**Issue by gavinr** [atoha/dbootstrap#59]
I'm on Windows 7, 64-bit.
Node version 0.10.6
Python 2.7
Stylus 0.32.1

When I run the python script it errors out:

```
C:\GitHub\dbootstrap>c:\Python27\python.exe build.py theme
INFO:dbootstrap.build:Building theme to C:\GitHub\dbootstrap\build\theme
INFO:dbootstrap.build:Building CSS.
INFO:dbootstrap.build:Building Javascript packages.
WARNING:dbootstrap.build.execute:Command node C:/GitHub/dbootstrap/source/dojo/d
ojo.js load=build --profile C:/GitHub/dbootstrap/resource/dbootstrap_profile.js
--releaseDir C:/GitHub/dbootstrap/build/theme exited with code -1
INFO:dbootstrap.build:Removing temporary and unnecessary files.
Traceback (most recent call last):
  File "build.py", line 306, in <module>
    raise SystemExit(main())
  File "build.py", line 163, in main
    shutil.rmtree(package_path)
  File "c:\Python27\lib\shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "c:\Python27\lib\shutil.py", line 237, in rmtree
    names = os.listdir(path)
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\GitHub\\
dbootstrap\\build\\theme\\dojo/*.*'
```

So I try to run the offending command to see what happens, and I'm getting this error:

```
C:\GitHub\dbootstrap>node C:/GitHub/dbootstrap/source/dojo/dojo.js load=build --
profile C:/GitHub/dbootstrap/resource/dbootstrap_profile.js --releaseDir C:/GitH
ub/dbootstrap/build/theme
processing profile resource C:/GitHub/dbootstrap/resource/dbootstrap_profile.js
info(107) Package Version: package: dojo; version: 1.8.4
processing profile resource C:/GitHub/dbootstrap/source/dojo/dojo.profile.js
info(107) Package Version: package: dijit; version: 1.8.4
processing profile resource C:/GitHub/dbootstrap/source/dijit/dijit.profile.js
processing profile resource C:/GitHub/dbootstrap/source/xstyle/package.js
processing profile resource C:/GitHub/dbootstrap/source/dbootstrap/package.js
discovering resources...
starting reading resources...
starting processing raw resource content...
starting tokenizing resource...
starting processing resource tokens...
starting parsing resource...
{ [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

Any ideas on what's going on here? Thanks!

**Comment by martinpengellyphillips** [comment]
Hmmm. Do you have Java installed?

**Comment by gavinr** [comment]
No. Should I? I didn't see it as a dependency.

**Comment by martinpengellyphillips** [comment]
Yeah,  some parts of the Dojo build still use Java. And you're right,  I forgot to add that to the dependencies list so will fix that!

**Comment by gavinr** [comment]
Looks good. Thanks!!
