### ISSUE TITLE
build error : os.path.join(dbootstrap_theme_path, 'index.styl')

### ISSUE THREAD

**Issue by luluprat** [atoha/dbootstrap#95]
hello i can't build the dbootstrap.
i am on linux and try it on ubuntu and centos .
i have got the same issue : 
DEBUG:dbootstrap.build.execute:Running command: stylus --include /var/www/html/DEV/dbootstrap/source/nib/lib --include /var/www/html/DEV/dbootstrap/source/dbootstrap/theme/dbootstrap /var/www/html/DEV/dbootstrap/source/dbootstrap/theme/dbootstrap/index.styl
Traceback (most recent call last):
  File "build.py", line 308, in <module>
    raise SystemExit(main())
  File "build.py", line 66, in main
    os.path.join(dbootstrap_theme_path, 'index.styl')
  File "build.py", line 254, in execute
    str(error)
**main**.CommandExecutionException: stylus --include /var/www/html/DEV/dbootstrap/source/nib/lib --include /var/www/html/DEV/dbootstrap/source/dbootstrap/theme/dbootstrap /var/www/html/DEV/dbootstrap/source/dbootstrap/theme/dbootstrap/index.styl failed due to error: [Errno 2] No such file or directory.

any help.

**Comment by martinpengellyphillips** [comment]
Hi. Is 'stylus' installed and can you run it from the command line?

Typically, this error means that 'stylus' could not be found.

**Comment by luluprat** [comment]
Hello
i install stylus with 
npm install stylus -g
but when i try
stylus --version
it works but thre is no answer.

i still have the problem

python build.py demo
INFO:dbootstrap.build:Building demo to /var/www/dbootstrap/build/demo
INFO:dbootstrap.build:Building CSS.
WARNING:dbootstrap.build.execute:Command stylus --include /var/www/dbootstrap/source/nib/lib --include /var/www/dbootstrap/source/dbootstrap/theme/dbootstrap /var/www/dbootstrap/source/dbootstrap/theme/dbootstrap/index.styl exited with code 1
Traceback (most recent call last):
  File "build.py", line 308, in <module>
    raise SystemExit(main())
  File "build.py", line 77, in main
    dbootstrap_css_path
OSError: [Errno 2] No such file or directory

**Comment by PoyangLiu** [comment]
I have the same problem, but on windows machine.
runing "stylus --version" returns "0.42.3"
running "python build.py theme" gives the same error

d:\Projects\thesociable-dbootstrap-9d88eac>python build.py theme
INFO:dbootstrap.build:Building theme to d:\Projects\thesociable-dbootstrap-9d88e
ac\build\theme
INFO:dbootstrap.build:Building CSS.
WARNING:dbootstrap.build.execute:Command stylus.cmd --include d:\Projects\thesoc
iable-dbootstrap-9d88eac\source\nib\lib --include d:\Projects\thesociable-dboots
trap-9d88eac\source\dbootstrap\theme\dbootstrap d:\Projects\thesociable-dbootstr
ap-9d88eac\source\dbootstrap\theme\dbootstrap\index.styl exited with code 8
Traceback (most recent call last):
  File "build.py", line 308, in <module>
    raise SystemExit(main())
  File "build.py", line 77, in main
    dbootstrap_css_path
WindowsError: [Error 2] The system cannot find the file specified

**Comment by luluprat** [comment]
hello,

my problem was solved in removing node.js debian package and compiling
node.js.
maybe it helps

2014-03-07 19:48 GMT+01:00 Jay notifications@github.com:

**Comment by martinpengellyphillips** [comment]
If you want to try a prebuilt copy of the theme you can find it now under releases at https://github.com/thesociable/dbootstrap/releases
